```{r}
#Clear everything out, its probably messy from the data prep file
rm(list = ls())

#Packages we will need
library(reproducible) #setting up directories for data management
library(dplyr)        #data wranglin'
library(ggplot2)      #data visualization
library(stringr)      #reading information on strings
library(secr)         #the actual model engine
library(rgdal)        #dealing with spatial data

#Set the working directories to read in the files we need
input_directory<-reproducible::checkPath(file.path(getwd(), "2. SECR Prep/outputs"), create = TRUE)
output_directory<-reproducible::checkPath(file.path(getwd(), "3. SECR Models/outputs"), create = TRUE)



```


2018 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2018<-read.capthist(captfile = file.path(input_directory, "captures_2018.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2018.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2018)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2018, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2018<-addSightings(deer_secr_2018, unmarked = file.path(input_directory, "unmarked_matrix_2018.txt"), skip = 1)
summary(deer_secr_2018)
#And now fit the model with the unmarked sightings included
fit1_2018<-secr.fit(deer_secr_2018, buffer = 1000,trace = TRUE)
fit1_2018


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2018<-(summary(fit1_2018)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2018<-(summary(fit1_2018)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2018<-(summary(fit1_2018)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2018
upper_density_CI_2018
lower_density_CI_2018


#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2018 <- secr.fit(deer_secr_2018, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                 start = fit1_2018, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2018

#Save this so you don't have to run it again in the future
save(fit2_2018, file = file.path(output_directory, "fit2_2018.RData"))



```

2021 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2021<-read.capthist(captfile = file.path(input_directory, "captures_2021.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2021.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2021)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2021, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2021<-addSightings(deer_secr_2021, unmarked = file.path(input_directory, "unmarked_matrix_2021.txt"), skip = 1)
summary(deer_secr_2021)
#And now fit the model with the unmarked sightings included
fit1_2021<-secr.fit(deer_secr_2021, buffer = 1000,trace = TRUE)
fit1_2021


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2021<-(summary(fit1_2021)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2021<-(summary(fit1_2021)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2021<-(summary(fit1_2021)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2021
upper_density_CI_2021
lower_density_CI_2021


#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2021 <- secr.fit(deer_secr_2021, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                 start = fit1_2021, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2021

#Save this so you don't have to run it again in the future
save(fit2_2021, file = file.path(output_directory, "fit2_2021.RData"))




```


2023 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2023<-read.capthist(captfile = file.path(input_directory, "captures_2023.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2023.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2023)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2023, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2023<-addSightings(deer_secr_2023, unmarked = file.path(input_directory, "unmarked_matrix_2023.txt"), skip = 1)
summary(deer_secr_2023)
#And now fit the model with the unmarked sightings included
fit1_2023<-secr.fit(deer_secr_2023, buffer = 1000,trace = TRUE)
fit1_2023


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2023<-(summary(fit1_2023)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2023<-(summary(fit1_2023)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2023<-(summary(fit1_2023)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2023
upper_density_CI_2023
lower_density_CI_2023


#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2018 <- secr.fit(deer_secr_2018, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                 start = fit1_2018, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2018

#Save this so you don't have to run it again in the future
save(fit2_2018, file = file.path(output_directory, "fit2_2018.RData"))




```

Plots
```{r}
density_estimates<-data.frame(year= c(2018, 2023),
                              mean_density = c(mean_density_2018,  mean_density_2023),
           upper = c(upper_density_CI_2018, upper_density_CI_2023),
           lower = c(lower_density_CI_2018, lower_density_CI_2023))


library(ggtext) #For the superscript
density_estimate_figure<-ggplot(density_estimates, aes(x = as.factor(year), y = mean_density))+
  geom_point()+
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)+
  #ylab("Anthropogenic SO<sub>4</sub><sup>2-</sup> (ngm<sup>-3</sup>)")+
  ylab("Individuals<sup>-km2</sup> \u00B1 95% CI")+
  xlab("Year")+
  theme_classic()+
  theme(axis.text.y =element_text(size = 12, color = "black"),
        axis.title.y =element_markdown(size = 15, face = "bold", color = "black"),
        axis.text.x = element_text(size = 15, color = "black"),
        axis.title.x = element_blank())

ggsave(filename = "density_estimate_figure.jpeg", #name of file
       plot = density_estimate_figure,                 #plot you want to save
       path = output_directory,            #where it's saved
       width = 3500,                       #how wide
       height = 2000,                      #how tall
        units = "px",                      #units in pixels
        bg = 'white')   




```