
```{r}
#Clear everything out, its probably messy from the data prep file
rm(list = ls())

#Packages we will need
library(reproducible) #setting up directories for data management
library(dplyr)        #data wranglin'
library(ggplot2)      #data visualization
library(stringr)      #reading information on strings
library(secr)         #the actual model engine
#library(rgdal)        #dealing with spatial data

#Set the working directories to read in the files we need
input_directory<-reproducible::checkPath(file.path(getwd(), "2. SECR Prep/outputs"), create = TRUE)
output_directory<-reproducible::checkPath(file.path(getwd(), "3. SECR Models/outputs"), create = TRUE)
shapefile_directory<-reproducible::checkPath(file.path(getwd(), "3. SECR Models/shapefiles2"), create = TRUE)



```

2018 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2018<-read.capthist(captfile = file.path(input_directory, "captures_2018.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2018.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2018)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2018, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2018<-addSightings(deer_secr_2018, unmarked = file.path(input_directory, "unmarked_matrix_2018.txt"), skip = 1)
summary(deer_secr_2018)
#And now fit the model with the unmarked sightings included
fit1_2018<-secr.fit(deer_secr_2018, buffer = 1000,trace = TRUE)
fit1_2018


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2018<-(summary(fit1_2018)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2018<-(summary(fit1_2018)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2018<-(summary(fit1_2018)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2018
upper_density_CI_2018
lower_density_CI_2018

save(fit1_2018, file = file.path(output_directory, "fit1_2018.RData"))



#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2018 <- secr.fit(deer_secr_2018, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                 start = fit1_2018, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2018

#Save this so you don't have to run it again in the future
save(fit2_2018, file = file.path(output_directory, "fit2_2018.RData"))



```

2019 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2019<-read.capthist(captfile = file.path(input_directory, "captures_2019.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2019.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,35), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2019)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2019, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2019<-addSightings(deer_secr_2019, unmarked = file.path(input_directory, "unmarked_matrix_2019.txt"), skip = 1)
summary(deer_secr_2019)
#And now fit the model with the unmarked sightings included
fit1_2019<-secr.fit(deer_secr_2019, buffer = 1000,trace = TRUE)
fit1_2019


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2019<-(summary(fit1_2019)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2019<-(summary(fit1_2019)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2019<-(summary(fit1_2019)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2019
upper_density_CI_2019
lower_density_CI_2019


#Save this so you don't have to run it again in the future
save(fit1_2019, file = file.path(output_directory, "fit2_2019.RData"))

#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2019 <- secr.fit(deer_secr_2019, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                 start = fit1_2019, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2019

#Save this so you don't have to run it again in the future
save(fit2_2019, file = file.path(output_directory, "fit2_2019.RData"))



```



2020 model specification
```{r}
#Create a capture history object using the above created text files
deer_secr_2020<-read.capthist(captfile = file.path(input_directory, "captures_2020.txt"), 
                              trapfile = file.path(input_directory, "deer_cameras_2020.txt"),
                              detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                              #but allows >1 detection per animal per time
                              markocc = rep(0,35), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                              skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                              verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2020)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2020, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2020<-addSightings(deer_secr_2020, unmarked = file.path(input_directory, "unmarked_matrix_2020.txt"), skip = 1)
summary(deer_secr_2020)
#And now fit the model with the unmarked sightings included
fit1_2020<-secr.fit(deer_secr_2020, buffer = 1000,trace = TRUE)
fit1_2020

#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2020<-(summary(fit1_2020)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2020<-(summary(fit1_2020)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2020<-(summary(fit1_2020)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2020
upper_density_CI_2020
lower_density_CI_2020

save(fit1_2020, file = file.path(output_directory, "fit1_2020.RData"))



#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2020 <- secr.fit(deer_secr_2020, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                      start = fit1_2020, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2020

save(fit2_2020, file = file.path(output_directory, "fit2_2020.RData"))




```

2021 model specification yoooo
```{r}
#Create a capture history object using the above created text files
deer_secr_2021<-read.capthist(captfile = file.path(input_directory, "captures_2021.txt"), 
                              trapfile = file.path(input_directory, "deer_cameras_2021.txt"),
                              detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                              #but allows >1 detection per animal per time
                              markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                              skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                              verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2021)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2021, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2021<-addSightings(deer_secr_2021, unmarked = file.path(input_directory, "unmarked_matrix_2021.txt"), skip = 1)
summary(deer_secr_2021)
#And now fit the model with the unmarked sightings included
fit1_2021<-secr.fit(deer_secr_2021, buffer = 1000,trace = TRUE)
fit1_2021


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2021<-(summary(fit1_2021)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2021<-(summary(fit1_2021)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2021<-(summary(fit1_2021)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2021
upper_density_CI_2021
lower_density_CI_2021

save(fit1_2021, file = file.path(output_directory, "fit1_2021.RData"))


#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2021 <- secr.fit(deer_secr_2021, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                      start = fit1_2021, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2021

save(fit2_2021, file = file.path(output_directory, "fit2_2021.RData"))




```

2022 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2022<-read.capthist(captfile = file.path(input_directory, "captures_2022.txt"), 
                              trapfile = file.path(input_directory, "deer_cameras_2022.txt"),
                              detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                              #but allows >1 detection per animal per time
                              markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                              skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                              verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2022)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2022, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2022<-addSightings(deer_secr_2022, unmarked = file.path(input_directory, "unmarked_matrix_2022.txt"), skip = 1)
summary(deer_secr_2022)
#And now fit the model with the unmarked sightings included
fit1_2022<-secr.fit(deer_secr_2022, buffer = 1000,trace = TRUE)
fit1_2022


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2022<-(summary(fit1_2022)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2022<-(summary(fit1_2022)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2022<-(summary(fit1_2022)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2022
upper_density_CI_2022
lower_density_CI_2022

save(fit1_2022, file = file.path(output_directory, "fit1_2022.RData"))


#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2022 <- secr.fit(deer_secr_2022, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                      start = fit1_2022, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2022

save(fit2_2022, file = file.path(output_directory, "fit2_2022.RData"))

mean_density_2022<-(summary(fit2_2022)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2022<-(summary(fit2_2022)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2022<-(summary(fit2_2022)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2022
upper_density_CI_2022
lower_density_CI_2022



```


2023 Model
```{r}
#Create a capture history object using the above created text files
deer_secr_2023<-read.capthist(captfile = file.path(input_directory, "captures_2023.txt"), 
                              trapfile = file.path(input_directory, "deer_cameras_2023.txt"),
                              detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                              #but allows >1 detection per animal per time
                              markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                              skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                              verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
summary(deer_secr_2023)

#This shows a plot of detections for individuals
#Good to inspect that you dont have an individual located on traps on completely different 
#sides of the study area (unlikely, would indicate an error likely - unless the move A LOT)
plot(deer_secr_2023, tracks = TRUE)

#Lets add the unmarked sightings to the capture history object
deer_secr_2023<-addSightings(deer_secr_2023, unmarked = file.path(input_directory, "unmarked_matrix_2023.txt"), skip = 1)
summary(deer_secr_2023)
#And now fit the model with the unmarked sightings included
fit1_2023<-secr.fit(deer_secr_2023, buffer = 1000,trace = TRUE)
fit1_2023


#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2023<-(summary(fit1_2023)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2023<-(summary(fit1_2023)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2023<-(summary(fit1_2023)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2023
upper_density_CI_2023
lower_density_CI_2023

save(fit1_2023, file = file.path(output_directory, "fit1_2023.RData"))


#What about overdispersion??
#1. fit the model ASSUMING NO OVERDISPERSION
#2. Estimate the overdispersion by simulating at the initial estimates
#3. Re-fit the model using an overdispersion-adjusted pseudo-likelioo
fit2_2023 <- secr.fit(deer_secr_2023, buffer = 1000, trace = FALSE, #this lines repeats the model specification from fit1
                      start = fit1_2023, details = list(nsim = 10000)) #this line gives the previous model fit1 as a starting point, calls nsim simulations to estimated overdispersion (c-hat)

fit2_2023

save(fit2_2023, file = file.path(output_directory, "fit2_2023.RData"))

mean_density_2023<-(summary(fit2_2023)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2023<-(summary(fit2_2023)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2023<-(summary(fit2_2023)[["predicted"]][["lcl"]][[1]]) *100
mean_density_2023
upper_density_CI_2023
lower_density_CI_2023



```

Baseline density estimate plot
```{r}
#Load in the data we need
load(file.path(output_directory, "fit1_2018.RData"))
load(file.path(output_directory, "fit2_2019.RData"))
load(file.path(output_directory, "fit1_2020.RData"))
load(file.path(output_directory, "fit1_2021.RData"))
load(file.path(output_directory, "fit2_2022.RData"))
load(file.path(output_directory, "fit1_2023.RData"))


#Extract the estimates for each year and wrap them into a dataframe
#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2018<-(summary(fit1_2018)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2018<-(summary(fit1_2018)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2018<-(summary(fit1_2018)[["predicted"]][["lcl"]][[1]]) *100

mean_density_2019<-(summary(fit1_2019)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2019<-(summary(fit1_2019)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2019<-(summary(fit1_2019)[["predicted"]][["lcl"]][[1]]) *100

mean_density_2020<-(summary(fit1_2020)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2020<-(summary(fit1_2020)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2020<-(summary(fit1_2020)[["predicted"]][["lcl"]][[1]]) *100


mean_density_2021<-(summary(fit1_2021)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2021<-(summary(fit1_2021)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2021<-(summary(fit1_2021)[["predicted"]][["lcl"]][[1]]) *100

mean_density_2022<-(summary(fit2_2022)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2022<-(summary(fit2_2022)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2022<-(summary(fit2_2022)[["predicted"]][["lcl"]][[1]]) *100

mean_density_2023<-(summary(fit1_2023)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2023<-(summary(fit1_2023)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2023<-(summary(fit1_2023)[["predicted"]][["lcl"]][[1]]) *100

density_estimates<-data.frame(year= c(2018, 2019, 2020, 2021, 2022, 2023),
                              mean_density = c(mean_density_2018, mean_density_2019, mean_density_2020, mean_density_2021, mean_density_2022, mean_density_2023),
           upper = c(upper_density_CI_2018, upper_density_CI_2019, upper_density_CI_2020, upper_density_CI_2021, upper_density_CI_2022, upper_density_CI_2023),
           lower = c(lower_density_CI_2018, lower_density_CI_2019, lower_density_CI_2020, lower_density_CI_2021, lower_density_CI_2022, lower_density_CI_2023))


library(ggtext) #For the superscript
ggplot(density_estimates, aes(x = as.factor(year), y = mean_density))+
  geom_point()+
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)+
  #ylab("Anthropogenic SO<sub>4</sub><sup>2-</sup> (ngm<sup>-3</sup>)")+
  ylab("Individuals<sup>-km2</sup> \u00B1 95% CI")+
  xlab("Year")+
  ggtitle("Preliminary Oak Bay Deer Density Estimates")+
  theme_classic()+
  theme(axis.text.y =element_text(size = 12, color = "black"),
        axis.title.y =element_markdown(size = 15, face = "bold", color = "black"),
        axis.text.x = element_text(size = 15, color = "black"),
         axis.title.x = element_blank())
```


At the end of that, save the R data
```{r}
load(file.path(output_directory, "fit2_2018.RData"))
load(file.path(output_directory, "fit2_2020.RData"))
load(file.path(output_directory, "fit2_2021.RData"))
load(file.path(output_directory, "fit2_2022.RData"))

#FILL THIS IN LATER

```

Plots and estimates
```{r}
#2018 Data################################################################################
#Inspect the measure of dispersion -> quite high
fit2_2018$details$chat

#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2018<-(summary(fit2_2018)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2018<-(summary(fit2_2018)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2018<-(summary(fit2_2018)[["predicted"]][["lcl"]][[1]]) *100

#extract mask area (ha) and convert to km squared
mask_area_2018<-(summary(fit2_2018)[["mask"]][["Area"]])/100

#predicted number of deer
mean_density_2018*mask_area_2018

#2020 Data#############################################################################
#Inspect the measure of dispersion -> quite high
fit2_2020$details$chat

#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2020<-(summary(fit2_2020)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2020<-(summary(fit2_2020)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2020<-(summary(fit2_2020)[["predicted"]][["lcl"]][[1]]) *100

#extract mask area (ha) and convert to km squared
mask_area_2020<-(summary(fit2_2020)[["mask"]][["Area"]])/100

#predicted number of deer
mean_density_2020*mask_area_2020

#2021 Data ##############################################################################
#Inspect the measure of dispersion -> quite high
fit2_2021$details$chat

#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2021<-(summary(fit2_2021)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2021<-(summary(fit2_2021)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2021<-(summary(fit2_2021)[["predicted"]][["lcl"]][[1]]) *100

#extract mask area (ha) and convert to km squared
mask_area_2021<-(summary(fit2_2021)[["mask"]][["Area"]])/100

#predicted number of deer
mean_density_2021*mask_area_2021

#2022 Data ##############################################################################
#Inspect the measure of dispersion -> quite high
fit2_2022$details$chat

#Extract estimate (deer/ha) and convert to deer per km2
mean_density_2022<-(summary(fit2_2022)[["predicted"]][["estimate"]][[1]]) *100
upper_density_CI_2022<-(summary(fit2_2022)[["predicted"]][["ucl"]][[1]]) *100
lower_density_CI_2022<-(summary(fit2_2022)[["predicted"]][["lcl"]][[1]]) *100

#extract mask area (ha) and convert to km squared
mask_area_2022<-(summary(fit2_2022)[["mask"]][["Area"]])/100

#predicted number of deer
mean_density_2022*mask_area_2022


#Lets make a plot of the density estimates
####################Plots!

library(ggtext)

density_estimates<-data.frame(year= c(2018, 2020, 2021, 2022),
                              mean_density = c(mean_density_2018, mean_density_2020, mean_density_2021, mean_density_2022),
           upper = c(upper_density_CI_2018, upper_density_CI_2020, upper_density_CI_2021, upper_density_CI_2022),
           lower = c(lower_density_CI_2018, lower_density_CI_2020, lower_density_CI_2021, lower_density_CI_2022))


library(ggtext) #For the superscript
density_estimate_figure<-ggplot(density_estimates, aes(x = as.factor(year), y = mean_density))+
  geom_point()+
  geom_errorbar(aes(ymin = lower, ymax = upper), width = 0.2)+
  #ylab("Anthropogenic SO<sub>4</sub><sup>2-</sup> (ngm<sup>-3</sup>)")+
  ylab("Individuals<sup>-km2</sup> \u00B1 95% CI")+
  xlab("Year")+
  theme_classic()+
  theme(axis.text.y =element_text(size = 12, color = "black"),
        axis.title.y =element_markdown(size = 15, face = "bold", color = "black"),
        axis.text.x = element_text(size = 15, color = "black"),
        axis.title.x = element_blank())

ggsave(filename = "density_estimate_figure.jpeg", #name of file
       plot = density_estimate_figure,                 #plot you want to save
       path = output_directory,            #where it's saved
       width = 3500,                       #how wide
       height = 2000,                      #how tall
        units = "px",                      #units in pixels
        bg = 'white')                      #make sure background is white



```