The purpose of this code is to prepare the habitat masks to be used by the multi session model


```{r}
#Clear everything out, its probably messy from the data prep file
rm(list = ls())

#Packages we will need
library(reproducible) #setting up directories for data management
library(dplyr)        #data wranglin'
library(lubridate)    #datetime data
library(ggplot2)      #data visualization
library(stringr)      #reading information on strings
library(secr)         #the actual model engine
library(rgdal)        #dealing with spatial data

#Set the working directories to read in the files we need
input_directory<-reproducible::checkPath(file.path(getwd(), "2. SECR Prep/outputs"), create = TRUE)
output_directory<-reproducible::checkPath(file.path(getwd(), "3. SECR Models/outputs"), create = TRUE)


```

The first thing I need to do is fit some preliminary models just to inform mask area and buffer suggestions. First create a capture history object
```{r}
#2018 Data First
#######################################
#Create a capture history object using the above created text files
deer_secr_2018<-read.capthist(captfile = file.path(input_directory, "captures_2018.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2018.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
#Lets add the unmarked sightings to the capture history object
deer_secr_2018<-addSightings(deer_secr_2018, unmarked = file.path(input_directory, "unmarked_matrix_2018.txt"), skip = 1)


#Pilot estimate for buffer width
RPSV(deer_secr_2018, CC= TRUE)

#Fit the model based on a starting buffer of 1000m
fit_2018<-secr.fit(deer_secr_2018, buffer = 1000,trace = TRUE, 
                       detectfn = "HN", #Half normal detection function
                       binomN = 0) 

#What is the suggested buffer?
suggest.buffer(fit_2018)

#Ok now lets check out the plot
par(pty = "s", mar = c(4,4,2,2), mgp = c(2.5, 0.8, 0), las = 1)
esa.plot(fit_2018, ylim = c(0,10))
abline(v = 4*RPSV(deer_secr_2018, CC= TRUE), col = "red", lty = 2 )
abline(v = suggest.buffer(fit_2018), col = "blue", lty = 2 )


```



```{r}
#2021 Data 
#######################################
#Create a capture history object using the above created text files
deer_secr_2021<-read.capthist(captfile = file.path(input_directory, "captures_2021.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2021.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
#Lets add the unmarked sightings to the capture history object
deer_secr_2021<-addSightings(deer_secr_2021, unmarked = file.path(input_directory, "unmarked_matrix_2021.txt"), skip = 1)


#Pilot estimate for buffer width
RPSV(deer_secr_2021, CC= TRUE)

#Fit the model based on a starting buffer of 1000m
fit_2021<-secr.fit(deer_secr_2021, buffer = 1000,trace = TRUE, 
                       detectfn = "HN", #Half normal detection function
                       binomN = 0) 

#What is the suggested buffer?
suggest.buffer(fit_2021)

#Ok now lets check out the plot
par(pty = "s", mar = c(4,4,2,2), mgp = c(2.5, 0.8, 0), las = 1)
esa.plot(fit_2018, ylim = c(0,10))
abline(v = 4*RPSV(deer_secr_2021, CC= TRUE), col = "red", lty = 2 )
abline(v = suggest.buffer(fit_2021), col = "blue", lty = 2 )


```

```{r}
#2021 Data 
#######################################
#Create a capture history object using the above created text files
deer_secr_2021<-read.capthist(captfile = file.path(input_directory, "captures_2021.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2021.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
#Lets add the unmarked sightings to the capture history object
deer_secr_2021<-addSightings(deer_secr_2021, unmarked = file.path(input_directory, "unmarked_matrix_2021.txt"), skip = 1)


#Pilot estimate for buffer width
RPSV(deer_secr_2021, CC= TRUE)

#Fit the model based on a starting buffer of 1000m
fit_2021<-secr.fit(deer_secr_2021, buffer = 1000,trace = TRUE, 
                       detectfn = "HN", #Half normal detection function
                       binomN = 0) 

#What is the suggested buffer?
suggest.buffer(fit_2021)

#Ok now lets check out the plot
par(pty = "s", mar = c(4,4,2,2), mgp = c(2.5, 0.8, 0), las = 1)
esa.plot(fit_2021, ylim = c(0,10))
abline(v = 4*RPSV(deer_secr_2021, CC= TRUE), col = "red", lty = 2 )
abline(v = suggest.buffer(fit_2021), col = "blue", lty = 2 )


```

```{r}
#2022 Data 
#######################################
#Create a capture history object using the above created text files
deer_secr_2022<-read.capthist(captfile = file.path(input_directory, "captures_2022.txt"), 
                         trapfile = file.path(input_directory, "deer_cameras_2022.txt"),
                         detector = "count", #this is a proximity detector (records presence at a point without restricting movement)
                         #but allows >1 detection per animal per time
                         markocc = rep(0,30), #This is a vector of n = number of occassions, all zeros indicate no marking done, this is ALL resighting data
                         skip = 1, #Skip = 1 says don't read the first row, which is the headers!
                         verify = TRUE) #Checks to make sure sampling occassions, effort, etc. all match up    
#Lets add the unmarked sightings to the capture history object
deer_secr_2022<-addSightings(deer_secr_2022, unmarked = file.path(input_directory, "unmarked_matrix_2022.txt"), skip = 1)


#Pilot estimate for buffer width
RPSV(deer_secr_2022, CC= TRUE)

#Fit the model based on a starting buffer of 1000m
fit_2022<-secr.fit(deer_secr_2022, buffer = 1000,trace = TRUE, 
                       detectfn = "HN", #Half normal detection function
                       binomN = 0) 

#What is the suggested buffer?
suggest.buffer(fit_2022)

#Ok now lets check out the plot
par(pty = "s", mar = c(4,4,2,2), mgp = c(2.5, 0.8, 0), las = 1)
esa.plot(fit_2022, ylim = c(0,10))
abline(v = 4*RPSV(deer_secr_2022, CC= TRUE), col = "red", lty = 2 )
abline(v = suggest.buffer(fit_2022), col = "blue", lty = 2 )


```


Ok so at the end of all that I need to prep a couple masks and export them for the multi session model
```{r}
#I am going to use a 1000m buffer size just for demonstration purpose right now
#THIS IS ALSO NOT THE REAL MASK, I WILL NEED TO EXPORT THEM FROM ARCMAP


#2021 mask
#Ok first thing, read in the shape file
oak_bay_no_ocean_2021<-sf::st_read("2. SECR Prep/shapefiles/new_cams_Buffer1_Erase.shp")

#Now we make the mask based on the capthist file
mask_2021<-make.mask(traps(deer_secr_2021), type = "trapbuffer", buffer = 1000,
          poly = oak_bay_no_ocean_2021)
#What does the mask for this look like?
par(mar = c(1,1,1,1))
plot(mask_2021, dots = FALSE, mesh = "grey", col = "white")
plot(traps(deer_secr_2021), detpar = list(pch = 16, cex = 1), add = TRUE)

#summary stuff on mask
nrow(mask_2021)
maskarea(mask_2021)
maskarea(mask_2021)/100

#2022 mask
#Ok first thing, read in the shape file
oak_bay_no_ocean_2022<-sf::st_read("2. SECR Prep/shapefiles/new_cams_Buffer1_Erase.shp")

#Now we make the mask based on the capthist file
mask_2022<-make.mask(traps(deer_secr_2022), type = "trapbuffer", buffer = 1000,
          poly = oak_bay_no_ocean_2022)
#What does the mask for this look like?
par(mar = c(1,1,1,1))
plot(mask_2022, dots = FALSE, mesh = "grey", col = "white")
plot(traps(deer_secr_2022), detpar = list(pch = 16, cex = 1), add = TRUE)

#summary stuff on mask
nrow(mask_2022)
maskarea(mask_2022)
maskarea(mask_2022)/100



#Now export those masks for use in the multi session model
save(mask_2021, file = file.path(output_directory, "mask_2021.RData"))
save(mask_2022, file = file.path(output_directory, "mask_2022.RData"))


save(fit2_2022, file = file.path(output_directory, "fit2_2022.RData"))
```